# Generated by Django 2.2.13 on 2020-06-26 06:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('time_limit', models.DurationField(default=datetime.timedelta(0, 1), verbose_name='time limit')),
                ('input_file', models.CharField(blank=True, max_length=255, verbose_name='input file')),
                ('output_file', models.CharField(blank=True, max_length=255, verbose_name='output file')),
                ('description', models.TextField(verbose_name='description')),
                ('input', models.TextField(verbose_name='input')),
                ('output', models.TextField(verbose_name='output')),
            ],
            options={
                'verbose_name': 'problem',
                'verbose_name_plural': 'problems',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, verbose_name='input')),
                ('output', models.TextField(blank=True, verbose_name='output')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'test case',
                'verbose_name_plural': 'test cases',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('language', models.CharField(max_length=20, verbose_name='language')),
                ('source', models.TextField(blank=True, verbose_name='source')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('score', models.IntegerField(verbose_name='score')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem', verbose_name='problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('ONF', 'Output Not Found'), ('RE', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('UE', 'Unknown Error'), ('CE', 'Compilation Error')], max_length=3, verbose_name='status')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='duration')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Submission', verbose_name='submission')),
            ],
            options={
                'verbose_name': 'test point',
                'verbose_name_plural': 'test points',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, verbose_name='input')),
                ('output', models.TextField(blank=True, verbose_name='output')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'example',
                'verbose_name_plural': 'examples',
            },
        ),
    ]
