# Generated by Django 2.2.13 on 2020-06-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='language',
        ),
        migrations.AddField(
            model_name='submission',
            name='processor',
            field=models.TextField(default='{}', verbose_name='processor'),
        ),
    ]
