# Generated by Django 2.2.13 on 2020-06-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20200627_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='stderr',
            field=models.TextField(blank=True, verbose_name='standard error'),
        ),
        migrations.AddField(
            model_name='status',
            name='stdout',
            field=models.TextField(blank=True, verbose_name='standard output'),
        ),
    ]
