# Generated by Django 2.2.13 on 2020-06-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20200627_0152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='TestPoint',
        ),
    ]
